services:
 bot:
  build: .
  ports:
   - "8000:8000"
  env_file:
   - .env
  command: ["python", "bot/main.py"]
  volumes:
   - db_file:/app/users.db 

 app:
  build: .
  depends_on:
   - bot
  ports:
   - "5000:5000" 
  environment:
   - FLASK_ENV=production
   - FLASK_APP=app.main 
  command: ["/run-app.sh"]
  volumes:
   - db_file:/app/users.db

volumes:
 db_file:
